name: First Workflow

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-lasted
    steps:
      - name: echo a string
        run: echo "Hello World!"
      - name: Multiple Commands
        run: |
          node -v 
          npm -v