name: Workflow Commands
on: [push]

jobs:
  testing-wf-commands:
    runs-on: ubuntu-latest
    steps:
      - name: Create an anotation for build error
        run: echo "::error::Missing semicolon"
