name: Working Dirs and Shells
on: [push]
defaults: 
  run:
    shell: bash
    # working-directory: /de/ed
jobs:
  display-wd-info:
    runs-on: ubuntu-latest
    steps:
      - name: Display Working Directory and List Files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name: Change Working Directory
        working-directory: /home/runner
        run: pwd
  display-wd-info-windows:
    runs-on: windows-latest
    defaults: # override defaults setting in the head
      run:
        shell: pwsh
    steps:
      - name: Display Working Directory and List Files on Windows
        run: |
          Get-Location 
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name: Python Shell
        shell: python  # override defaults setting in Windows shell
        run: |
          import platform
          print(platform.processor())
